[build]
  command = "echo 'Static site - no build needed'"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
